/* Arbor of the Third Place — the voices of the six extra designs.
   Only the page's own wording is re-voiced here (headings, labels, microcopy, empty states, placeholders).
   Document IDs, titles, versions, counts and every figure read from the repository are never touched:
   they are always inserted by the page from DATA, not from this file.
   A key that a design does not define falls back to the Original (Codex) wording.
   B = the nine books: [label, name, short ja, heading ja, initial, index blurb or null]. */
const SKINS=[
  {id:"orig",ja:"聖典",en:"Codex",name:"Original"},
  {id:"s1",ja:"地形図",en:"Topographic Map"},
  {id:"s2",ja:"星図",en:"Star Chart"},
  {id:"s3",ja:"建築",en:"Architectural Set"},
  {id:"s4",ja:"植物図譜",en:"Botanical Plates"},
  {id:"s5",ja:"年輪",en:"Tree Rings"},
  {id:"s6",ja:"標本棚",en:"Specimen Cabinet"}
];
const TX={
/* ---------------------------------------------------------------- 地形図 */
s1:{
  rail:"Cartographia Arboris", capL:"Aerial View · Frontispiece",
  sub:"Topographic Survey of the Third Place",
  over:"The Third Place · 全文書の等高線図",
  ja:`第三の場所　<span class="m-nk"></span>書の地形図`,
  dek:`THE THIRD PLACE を形づくる<span class="m-nk"></span>の文書を、標高の高いほうから低いほうへ、一枚の地形図に測り直した。山頂は原典、麓は記録。九つの図幅が、基準点、稜線、地名索引、補給所、地質、凡例、境界、踏み跡、そして測量史を収める。記載はすべて、リポジトリ main の文書本文から生成している。`,
  figs:["Peaks · 文書","Ranges · 系列","Strata · 地層","Contours · 階層","Trails · 言及","Lines · 総行数"],
  idxh:"Sheet Index · 図幅索引",
  cta:"Gazetteer · 地名から全書を探す", fabA:"Locate", fabB:"地名検索",
  seekH:"Gazetteer", seekS:"地名索引で全書を引く", seekPh:"地名（語）を入力。空白で区切ると、すべてを含む行を探す",
  gFilter:"Locate", gPh:"補給所の物資を探す：ブランド・製品・素材・色・ID", more:"さらに読み進める",
  hint:"山頂を選ぶと文書録 · Select a summit",
  l2p:"高さは OP-001 §12 の情報階層に従う。山頂ほど優先され、麓の文書は上位を変更できない。三角は一つの文書、赤い破線の登山道は文書が明記する責任の受け渡し。山頂に触れると、その書の文書録が開く。",
  l8p:"行の文書が、列の文書のIDを本文中で何回書いているか。登山道が「定められた関係」なら、踏み跡は「実際に歩かれた回数」である。セルを選ぶと、行の文書が地形図の上で開く。",
  lg1k:"Colour · 山系の色", lg1p:"三角の色は系列を表す。原典と運用は土の色、記録の五系列はそれぞれ固有の色を持つ。",
  lg2k:"Ring · 輪", lg2p:"三角を囲む輪は権限区分（OP-008 §9.1）。唯一の正本だけが二重の輪を持つ。",
  lg3k:"Flag · 旗", lg3p:"山頂の旗は変動性（OP-008 §9.3）。台帳は風にはためき、規則と原典は旗を立てない。",
  lg4k:"Trails · 道", lg4p:"赤い破線の登山道は文書が明記する責任の受け渡し。選択時に現れる青い細線は、本文中で互いの文書IDに触れた回数。左右の稜線の配置は、この地形図による解釈である。",
  volA:["旗なし","ゆるやかに揺れる旗","はためく旗"],
  pathA:["責任の受け渡し（登山道）","情報階層の流れ","言及の線（沢）"],
  rootL:["Benchmarks · 支え","archive/ と scripts/"],
  pil:["WEST RIDGE · 感性","MAIN RIDGE · 原点","EAST RIDGE · 規律"],
  census:"Provisions · 備蓄", tlb:"This Survey",
  tab:["Aerial I","Aerial II","Aerial III","Aerial IV"],
  dToc:"Route · 登高の章立て", dEnt:"Caches · 登録項目", dProf:"Field Notes · どのような文書か", dHolds:"Carries · 管理対象",
  dRel:"Trails · 定められた関係", dOut:"Trails out · この文書が触れる", dIn:"Trails in · この文書に触れる",
  dSeek:"この図幅の中を検索", dGal:"補給所で見る", none:"なし",
  gEntries:"caches", sIntro:"を地名索引で引ける", sNone:"載っていない。語を減らすか、範囲を広げてください。", sAll:"All sheets",
  mnL:["most visited","busiest trail","reach all"],
  mnP:[t=>`${t}。最も多くの文書から踏まれた、人通りの多い山。`,(a,b)=>`${a} から ${b} へ。最も踏み固められた一本の踏み跡。`,(n,N)=>n?`他の ${N-1} 文書すべてに踏み跡を持つ書。`:`すべての山へ踏み跡を伸ばした書は、いまはない。`],
  B:[
    ["Sheet 1","Datum","基準点","基準点","D",null],
    ["Sheet 2","Summits","稜線","文書の稜線","S","情報階層を標高に見立てた稜線図と、各書の文書録"],
    ["Sheet 3","Gazetteer","地名索引","書目","G",null],
    ["Sheet 4","Caches","補給所","補給所","C","台帳に登録されたオブジェクトを一点ずつ札にした、補給所の目録"],
    ["Sheet 5","Geology","地質","三つの地層","G",null],
    ["Sheet 6","Legend","凡例","文書律","L",null],
    ["Sheet 7","Boundaries","境界","外との境界","B",null],
    ["Sheet 8","Trails","踏み跡","言及の踏み跡","T","本文中で交わされる文書IDの言及を、踏み跡の濃さで示した表"],
    ["Sheet 9","Surveys","測量史","改訂の測量史","S",null]
  ]
},
/* ---------------------------------------------------------------- 星図 */
s2:{
  rail:"Atlas Stellarum", capL:"Nox Prima · Frontispiece",
  sub:"Celestial Atlas of the Third Place",
  over:"The Third Place · 文書の星図",
  ja:`第三の場所　<span class="m-nk"></span>書の星図`,
  dek:`THE THIRD PLACE を形づくる<span class="m-nk"></span>の文書を、夜空に置き直した。原典は天の北極、文書は等級の違う星。言及の多い文書どうしを結ぶと、星座になる。九つの天図が、北極星、天球、星表、観測器械、軌道、運行の法、合、星座線、そして紀元を収める。記載はすべて、リポジトリ main の文書本文から生成している。`,
  figs:["Stars · 文書","Constellations · 系列","Orbits · 地層","Latitudes · 階層","Conjunctions · 言及","Lines · 総行数"],
  idxh:"Index Caeli · 天図の目次",
  cta:"Observatio · 全書を観測する", fabA:"Observe", fabB:"全書観測",
  seekH:"Observatio", seekS:"全書を観測する", seekPh:"星の名（語）を入力。空白で区切ると、すべてを含む行を探す",
  gFilter:"Observe", gPh:"観測器械を探す：ブランド・製品・素材・色・ID", more:"さらに観測する",
  hint:"星を選ぶと文書録 · Select a star",
  l2p:"中心は天の北極、原典 DS-001。外へ向かうほど情報階層は下り（OP-001 §12）、同心円の緯度が階層を示す。星の大きさは本文の行数、色は系列。実線は同じ系列の中で言及の多い文書を結んだ星座線、破線は文書が明記する責任の受け渡し。星に触れると、その書の文書録が開く。",
  l8p:"星座線のもとになった、言及の回数表。行の文書が、列の文書のIDを本文中で何回書いているか。破線が「定められた関係」なら、この表は「実際に呼び合った回数」である。セルを選ぶと、行の文書が星図の上で開く。",
  lg1k:"Colour · 星の色", lg1p:"星の色は系列を表す。原典は北極星の白金、運用は黄金、記録の五系列はそれぞれ固有の色を持つ。",
  lg2k:"Halo · 暈", lg2p:"星を囲む暈は権限区分（OP-008 §9.1）。唯一の正本だけが二重の暈を持つ。",
  lg3k:"Twinkle · 瞬き", lg3p:"星の瞬きは変動性（OP-008 §9.3）。台帳ほど激しく瞬き、規則と原典は動かない。",
  lg4k:"Lines · 星座線", lg4p:"実線の星座線は同じ系列の中で言及の多い文書を結ぶ。破線は文書が明記する責任の受け渡し。選択時に現れる細い光は、本文中で互いの文書IDに触れた回数。星の方位は、この星図による解釈である。",
  volA:["動かない","ゆっくり脈打つ","激しく瞬く"],
  pathA:["責任の受け渡し（破線）","情報階層の流れ","言及の光（細線）"],
  rootL:["Horizon · 支え","archive/ と scripts/"],
  census:"Inventarium · 収蔵", tlb:"This Atlas",
  tab:["Nox I","Nox II","Nox III","Nox IV"],
  dToc:"Meridian · 章立て", dEnt:"Instrumenta · 登録項目", dProf:"Notae · どのような文書か", dHolds:"Holds · 管理対象",
  dRel:"Lineae · 定められた関係", dOut:"Radii out · この文書が触れる", dIn:"Radii in · この文書に触れる",
  dSeek:"この天図の中を観測", dGal:"観測器械で見る", none:"なし",
  gEntries:"instruments", sIntro:"を観測できる", sNone:"観測できない。語を減らすか、範囲を広げてください。", sAll:"All charts",
  mnL:["most mentioned · brightest","strongest line","reach all"],
  mnP:[t=>`${t}。最も多くの文書から名を呼ばれる、いちばん明るい星。`,(a,b)=>`${a} から ${b} へ。最も太く光る一本の線。`,(n,N)=>n?`他の ${N-1} 文書すべてに光を届ける星。`:`すべての星に光を届ける星は、いまはない。`],
  B:[
    ["Chart 1","Polaris","北極星","北極星","P",null],
    ["Chart 2","Firmament","天球","文書の天球","F","情報階層を緯度に置いた極図と、各書の文書録"],
    ["Chart 3","Catalogus","星表","書目の星表","C",null],
    ["Chart 4","Instrumenta","観測器械","観測器械","I","台帳に登録されたオブジェクトを、一点ずつ観測器械の札にした目録"],
    ["Chart 5","Orbits","軌道","三つの軌道","O",null],
    ["Chart 6","Leges","運行の法","運行の法","L",null],
    ["Chart 7","Conjunctio","合","外との合","C",null],
    ["Chart 8","Lineae","星座線","言及の星座線","L","本文中で交わされる文書IDの言及。星座線のもとになった表"],
    ["Chart 9","Epocha","紀元","改訂の紀元","E",null]
  ]
},
/* ---------------------------------------------------------------- 建築 */
s3:{
  rail:"Drawing Set · Arbor", capL:"Site Photo · Frontispiece",
  sub:"Drawing Set of the Third Place",
  over:"The Third Place · 図面一式 · Issued for reference",
  ja:`第三の場所　<span class="m-nk"></span>書の図面集`,
  dek:`THE THIRD PLACE を形づくる<span class="m-nk"></span>の文書を、一式の図面に起こした。原典は基礎、記録は仕上げ。九枚の図面が、設計主旨、立面、図面表、什器、断面、仕様、契約、通り芯、そして改訂履歴を収める。記載はすべて、リポジトリ main の文書本文から生成している。`,
  figs:["Sheets · 文書","Series · 系列","Layers · 地層","Levels · 階層","References · 言及","Lines · 総行数"],
  idxh:"Drawing Index · 図面目録",
  cta:"Search Set · 図面一式を検索する", fabA:"Search", fabB:"図面検索",
  seekH:"Search Set", seekS:"図面一式を検索する", seekPh:"検索語。空白で区切ると、すべてを含む行を探す（AND）",
  gFilter:"Schedule", gPh:"什器を探す：ブランド・製品・素材・色・ID", more:"続きを表示",
  hint:"室を選ぶと文書録 · Select a room",
  l2p:"階は OP-001 §12 の情報階層に従う。上階の文書ほど優先され、下階の文書は上位を変更できない。矩形は一つの文書、実線の矢印は文書が明記する責任の受け渡し。室に触れると、その書の文書録が開く。",
  l8p:"行の文書が、列の文書のIDを本文中で何回書いているか。矢印が「定められた関係」なら、通り芯の交点の濃さは「実際に交わされた参照」の回数である。セルを選ぶと、行の文書が立面図の上で開く。",
  lg1k:"Tab · 色票", lg1p:"室の左端の色票は系列を表す。原典は黒、運用は青、記録の五系列はそれぞれ固有の色を持つ。",
  lg2k:"Wall · 壁", lg2p:"室を囲む壁線は権限区分（OP-008 §9.1）。唯一の正本だけが二重壁を持つ。",
  lg3k:"Hatch · 斜線", lg3p:"室内の斜線は変動性（OP-008 §9.3）。台帳ほど密な斜線（改修中）、規則と原典は無地。",
  lg4k:"Arrows · 矢印", lg4p:"実線の矢印は文書が明記する責任の受け渡し。選択時に現れる赤い細線は、本文中で互いの文書IDに触れた回数。各階の室の並びは、この図面による解釈である。",
  volA:["無地","まばらな斜線","密な斜線"],
  pathA:["責任の受け渡し（矢印）","情報階層の流れ","参照の線（赤）"],
  rootL:["Footings · 基礎","archive/ と scripts/"],
  census:"Schedule · 収蔵", tlb:"This Set",
  tab:["Photo I","Photo II","Photo III","Photo IV"],
  dToc:"Sections · 章立て", dEnt:"Schedule · 登録項目", dProf:"General Notes · どのような文書か", dHolds:"Scope · 管理対象",
  dRel:"Connections · 定められた関係", dOut:"References out · この文書が触れる", dIn:"References in · この文書に触れる",
  dSeek:"この図面の中を検索", dGal:"什器表で見る", none:"なし",
  gEntries:"items", sIntro:"を検索できる", sNone:"該当なし。語を減らすか、範囲を広げてください。", sAll:"All sheets",
  mnL:["most referenced","heaviest line","reach all"],
  mnP:[t=>`${t}。最も多くの文書から参照される、要の書。`,(a,b)=>`${a} から ${b} へ。最も太く引かれた一本の参照線。`,(n,N)=>n?`他の ${N-1} 文書すべてを参照する書。`:`他のすべての文書を参照する書は、いまはない。`],
  B:[
    ["Sheet 01","Brief","設計主旨","設計主旨","B",null],
    ["Sheet 02","Elevation","立面図","文書の立面図","E","情報階層を階に置いた立面図と、各書の文書録"],
    ["Sheet 03","Schedule","図面表","書目の図面表","S",null],
    ["Sheet 04","Fixtures","什器","什器備品","F","台帳に登録されたオブジェクトを一点ずつ什器表にした目録"],
    ["Sheet 05","Section","断面図","三つの地層の断面","S",null],
    ["Sheet 06","Specification","仕様書","文書律の仕様書","S",null],
    ["Sheet 07","Contract","契約図書","外との契約","C",null],
    ["Sheet 08","Grid","通り芯","言及の通り芯","G","本文中で交わされる文書IDの言及を、通り芯の交点で示した表"],
    ["Sheet 09","Revisions","改訂履歴","改訂履歴","R",null]
  ]
},
/* ---------------------------------------------------------------- 植物図譜 */
s4:{
  rail:"Flora Arboris", capL:"Tab. Prima · Frontispiece",
  sub:"Flora of the Third Place",
  over:"The Third Place · 文書の植物図譜",
  ja:`第三の場所　<span class="m-nk"></span>書の図譜`,
  dek:`THE THIRD PLACE を形づくる<span class="m-nk"></span>の文書を、一株の樹として写生した。実は動かぬ文書、葉は折々に改まる文書、花は絶えず咲き替わる台帳。九つの図版が、種子、樹姿、目録、果実、土壌、分類、共生、菌糸、そして物候を収める。記載はすべて、リポジトリ main の文書本文から生成している。`,
  figs:["Specimens · 文書","Genera · 系列","Soil layers · 地層","Whorls · 階層","Hyphae · 言及","Lines · 総行数"],
  idxh:"Index Plantarum · 図版の目次",
  cta:"Index Nominum · 全書を名で引く", fabA:"Index", fabB:"全書検索",
  seekH:"Index Nominum", seekS:"全書を名で引く", seekPh:"名（語）を入力。空白で区切ると、すべてを含む行を探す",
  gFilter:"Collect", gPh:"果実を探す：ブランド・製品・素材・色・ID", more:"さらに採集する",
  hint:"一葉を選ぶと文書録 · Select a specimen",
  l2p:"高さは OP-001 §12 の情報階層に従う。上の文書ほど優先され、下の文書は上位を変更できない。実は動かぬ文書、葉は折々に改まる文書、花は絶えず咲き替わる文書。茎は文書が明記する責任の受け渡し。一枝に触れると、その書の文書録が開く。",
  l8p:"行の文書が、列の文書のIDを本文中で何回書いているか。茎が「定められた関係」なら、菌糸は「実際に交わされている言葉」である。セルを選ぶと、行の文書が図版の上で開く。",
  lg1k:"Colour · 彩色", lg1p:"彩色は系列を表す。原典は黄土、運用は苔色、記録の五系列はそれぞれ固有の色を持つ。",
  lg2k:"Calyx · 萼", lg2p:"実や葉、花を囲む輪は権限区分（OP-008 §9.1）。唯一の正本だけが二重の輪を持つ。",
  lg3k:"Habit · 姿", lg3p:"姿は変動性（OP-008 §9.3）。実は静止、葉はゆっくり改まり、花は絶えず咲き替わる。規則と原典は実を結び、台帳は花を咲かせる。",
  lg4k:"Stems · 茎", lg4p:"茎は文書が明記する責任の受け渡し。選択時に現れる細い線は、本文中で互いの文書IDに触れた回数。左右の枝ぶりは、この図譜による解釈である。",
  volA:["実 · 静止","葉 · ゆっくり改まる","花 · 咲き替わる"],
  pathA:["責任の受け渡し（茎）","情報階層の流れ","言及の菌糸"],
  rootL:["Radices · 根","archive/ と scripts/"],
  census:"Collectio · 収蔵", tlb:"This Flora",
  tab:["Tab. I","Tab. II","Tab. III","Tab. IV"],
  dToc:"Folia · 章立て", dEnt:"Fructus · 登録項目", dProf:"Descriptio · どのような文書か", dHolds:"Partes · 管理対象",
  dRel:"Rami · 定められた関係", dOut:"Hyphae out · この文書が触れる", dIn:"Hyphae in · この文書に触れる",
  dSeek:"この図版の中を検索", dGal:"果実を見る", none:"なし",
  gEntries:"fruits", sIntro:"を名で引ける", sNone:"載っていない。語を減らすか、範囲を広げてください。", sAll:"All plates",
  mnL:["most cited","strongest hypha","reach all"],
  mnP:[t=>`${t}。最も多くの文書から名を呼ばれる、根の太い書。`,(a,b)=>`${a} から ${b} へ。最も太く伸びた一本の菌糸。`,(n,N)=>n?`他の ${N-1} 文書すべてに菌糸を伸ばす書。`:`すべての文書に菌糸を伸ばす書は、いまはない。`],
  B:[
    ["Tab. 1","Semen","種子","原典の種子","S",null],
    ["Tab. 2","Habitus","樹姿","文書の樹姿","H","情報階層に沿って一株に写した樹姿と、各書の文書録"],
    ["Tab. 3","Herbarium","目録","書目の目録","H",null],
    ["Tab. 4","Fructus","果実","蒐集の果実","F","台帳に登録されたオブジェクトを一点ずつ果実の札にした目録"],
    ["Tab. 5","Solum","土壌","三つの地層","S",null],
    ["Tab. 6","Taxonomia","分類","文書律の分類","T",null],
    ["Tab. 7","Symbiosis","共生","外との共生","S",null],
    ["Tab. 8","Mycelium","菌糸","言及の菌糸","M","本文中で交わされる文書IDの言及を、菌糸の濃さで示した表"],
    ["Tab. 9","Phaenologia","物候","改訂の物候","P",null]
  ]
},
/* ---------------------------------------------------------------- 年輪 */
s5:{
  rail:"Annuli Arboris", capL:"Slice Prima · Frontispiece",
  sub:"Annual Rings of the Third Place",
  over:"The Third Place · 文書の年輪",
  ja:`第三の場所　<span class="m-nk"></span>書の年輪`,
  dek:`THE THIRD PLACE を形づくる<span class="m-nk"></span>の文書を、一本の幹の断面として切り出した。髄は原典、外へ向かうほど原典から遠い文書。外周の樹皮は、外の世界との契約である。九つの断面が、髄、幹、年輪帳、用材、三層、木目、樹皮、放射組織、そして年輪の記を収める。記載はすべて、リポジトリ main の文書本文から生成している。`,
  figs:["Knots · 文書","Species · 系列","Layers · 地層","Rings · 階層","Rays · 言及","Lines · 総行数"],
  idxh:"Index Annulorum · 年輪の目録",
  cta:"Core Sample · 全書から採取する", fabA:"Core", fabB:"全書採取",
  seekH:"Core Sample", seekS:"全書から採取する", seekPh:"語を入力。空白で区切ると、すべてを含む行を採る",
  gFilter:"Sample", gPh:"用材を探す：ブランド・製品・素材・色・ID", more:"さらに採取する",
  hint:"節を選ぶと文書録 · Select a knot",
  l2p:"髄から外へ、ひと巻きが一つの階層（OP-001 §12）。髄に近いほど優先され、外の文書は内側を変更できない。節は一つの文書、放射状の線は文書が明記する責任の受け渡し。ここに切り出したのは、幹の断面の扇形である。節に触れると、その書の文書録が開く。",
  l8p:"行の文書が、列の文書のIDを本文中で何回書いているか。放射状の線が「定められた関係」なら、放射組織は「実際に交わされている言葉」である。セルを選ぶと、行の文書が断面の上で開く。",
  lg1k:"Colour · 材の色", lg1p:"節の色は系列を表す。原典は淡い黄、運用は琥珀、記録の五系列はそれぞれ固有の色を持つ。",
  lg2k:"Ring · 輪", lg2p:"節を囲む輪は権限区分（OP-008 §9.1）。唯一の正本だけが二重の輪を持つ。",
  lg3k:"Pulse · 脈動", lg3p:"節の脈動は変動性（OP-008 §9.3）。台帳ほど呼吸が速く、規則と原典は動かない。",
  lg4k:"Rays · 放射線", lg4p:"放射状の線は文書が明記する責任の受け渡し。選択時に現れる細い線は、本文中で互いの文書IDに触れた回数。扇の中の並びは、この断面による解釈である。",
  volA:["動かない","ゆっくり脈打つ","速く脈打つ"],
  pathA:["責任の受け渡し（放射線）","情報階層の流れ","言及の放射組織"],
  rootL:["Roots · 根","archive/ と scripts/"],
  pil:["",  "", ""],
  census:"Timber · 収蔵", tlb:"This Section",
  tab:["Slice I","Slice II","Slice III","Slice IV"],
  dToc:"Growth · 章立て", dEnt:"Timber · 登録項目", dProf:"Grain Notes · どのような文書か", dHolds:"Holds · 管理対象",
  dRel:"Rays · 定められた関係", dOut:"Rays out · この文書が触れる", dIn:"Rays in · この文書に触れる",
  dSeek:"この断面の中を検索", dGal:"用材で見る", none:"なし",
  gEntries:"timbers", sIntro:"から採取できる", sNone:"採れない。語を減らすか、範囲を広げてください。", sAll:"All sections",
  mnL:["most cited","strongest ray","reach all"],
  mnP:[t=>`${t}。最も多くの文書から名を呼ばれる、年輪の深い書。`,(a,b)=>`${a} から ${b} へ。最も太く貫く一本の放射線。`,(n,N)=>n?`他の ${N-1} 文書すべてに放射線を伸ばす書。`:`すべての文書に放射線を伸ばす書は、いまはない。`],
  B:[
    ["Ring 1","Pith","髄","原典の髄","P",null],
    ["Ring 2","Truncus","幹","文書の幹","T","情報階層をひと巻きずつに写した断面と、各書の文書録"],
    ["Ring 3","Ringbook","年輪帳","書目の年輪帳","R",null],
    ["Ring 4","Timber","用材","用材の蔵","T","台帳に登録されたオブジェクトを一点ずつ用材札にした目録"],
    ["Ring 5","Wood","材の三層","三つの地層","W",null],
    ["Ring 6","Grain","木目","文書律の木目","G",null],
    ["Ring 7","Bark","樹皮","外との契約","B",null],
    ["Ring 8","Rays","放射組織","言及の放射組織","R","本文中で交わされる文書IDの言及を、放射組織の濃さで示した表"],
    ["Ring 9","Annals","年輪の記","改訂の年輪","A",null]
  ]
},
/* ---------------------------------------------------------------- 標本棚 */
s6:{
  rail:"Cabinet Arboris", capL:"Case Prima · Frontispiece",
  sub:"Cabinet of the Third Place",
  over:"The Third Place · 文書の標本棚",
  ja:`第三の場所　<span class="m-nk"></span>書の標本棚`,
  dek:`THE THIRD PLACE を形づくる<span class="m-nk"></span>の文書を、一棹の標本棚に収めた。段ごとに階層を分け、一点ずつ札を添え、関係のあるものは赤い糸で結んである。九つの抽斗が、来歴、陳列棚、目録、標本函、三段、陳列の律、貸与、結び糸、そして受入記録を収める。記載はすべて、リポジトリ main の文書本文から生成している。`,
  figs:["Specimens · 文書","Collections · 系列","Shelves · 地層","Drawers · 階層","Threads · 言及","Lines · 総行数"],
  idxh:"Index Capsarum · 抽斗の目次",
  cta:"Search Drawers · 全書の抽斗を探る", fabA:"Drawers", fabB:"全書検索",
  seekH:"Search Drawers", seekS:"全書の抽斗を探る", seekPh:"札の語を入力。空白で区切ると、すべてを含む行を探す",
  gFilter:"Find", gPh:"標本を探す：ブランド・製品・素材・色・ID", more:"さらに引き出す",
  hint:"標本を選ぶと文書録 · Select a specimen",
  l2p:"段は OP-001 §12 の情報階層に従う。上の段の文書ほど優先され、下の段の文書は上位を変更できない。ピンで留めた標本が一つの文書、赤い糸は文書が明記する責任の受け渡し。標本に触れると、その書の文書録が開く。",
  l8p:"行の文書が、列の文書のIDを本文中で何回書いているか。赤い糸が「定められた関係」なら、この表は「実際に結ばれた糸の数」である。セルを選ぶと、行の文書が標本棚の上で開く。",
  lg1k:"Colour · 標本の色", lg1p:"標本の色は系列を表す。原典は象牙、運用は真鍮、記録の五系列はそれぞれ固有の色を持つ。",
  lg2k:"Ring · 輪", lg2p:"標本を囲む輪は権限区分（OP-008 §9.1）。唯一の正本だけが二重の輪を持つ。",
  lg3k:"Pin · 留め方", lg3p:"標本の留め方は変動性（OP-008 §9.3）。台帳は付け替えのきく小さな針、規則と原典は動かない太いピン。",
  lg4k:"Thread · 糸", lg4p:"赤い糸は文書が明記する責任の受け渡し。選択時に現れる金の細糸は、本文中で互いの文書IDに触れた回数。段ごとの並びは、この標本棚による解釈である。",
  volA:["太いピンで固定","ゆっくり揺れるピン","付け替えのきく針"],
  pathA:["責任の受け渡し（赤い糸）","情報階層の流れ","言及の糸（金）"],
  rootL:["Reserve · 収蔵庫","archive/ と scripts/"],
  census:"Accession · 収蔵", tlb:"This Cabinet",
  tab:["Case I","Case II","Case III","Case IV"],
  dToc:"Label · 章立て", dEnt:"Specimens · 登録項目", dProf:"Label Text · どのような文書か", dHolds:"Contents · 管理対象",
  dRel:"Threads · 定められた関係", dOut:"Threads out · この文書が触れる", dIn:"Threads in · この文書に触れる",
  dSeek:"この抽斗の中を検索", dGal:"標本函で見る", none:"なし",
  gEntries:"specimens", sIntro:"の抽斗を探れる", sNone:"札がない。語を減らすか、範囲を広げてください。", sAll:"All drawers",
  mnL:["most threaded","tightest thread","reach all"],
  mnP:[t=>`${t}。最も多くの糸が結ばれた、棚の要。`,(a,b)=>`${a} から ${b} へ。最も固く結ばれた一本の糸。`,(n,N)=>n?`他の ${N-1} 文書すべてへ糸を結んだ書。`:`すべての文書へ糸を結んだ書は、いまはない。`],
  B:[
    ["Drawer 1","Provenance","来歴","原典の来歴","P",null],
    ["Drawer 2","Cabinet","陳列棚","文書の陳列棚","C","情報階層を段に置いた陳列棚と、各書の文書録"],
    ["Drawer 3","Catalogue","目録","書目の目録","C",null],
    ["Drawer 4","Specimens","標本函","標本函","S","台帳に登録されたオブジェクトを一点ずつ標本札にした目録"],
    ["Drawer 5","Shelves","三段","三つの棚","S",null],
    ["Drawer 6","Display","陳列の律","文書律の陳列","D",null],
    ["Drawer 7","Loans","貸与","外との貸借","L",null],
    ["Drawer 8","Threads","結び糸","言及の結び糸","T","本文中で交わされる文書IDの言及を、結び糸の数で示した表"],
    ["Drawer 9","Accession","受入記録","改訂の受入記録","A",null]
  ]
}
};
